/* cria a tabela de usuários */
CREATE TABLE "usuario" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" VARCHAR NOT NULL,
  "email" VARCHAR NOT NULL,
  "senha" VARCHAR NOT NULL
);
/* tabela de interesses */
CREATE TABLE "interesses" (
  "id_usuario" INT NOT NULL,
  "hobbies" VARCHAR,
  "filmes" VARCHAR,
  "series" VARCHAR,
  "musicas" VARCHAR
);

/* tabela de habitos */
CREATE TABLE "habitos" (
  "id_habito" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int,
  "titulo" varchar NOT NULL,
  "descricao" text,
  "frequencia_por_semana" int NOT NULL
);

/* tabela que registra o habito */
CREATE TABLE "registro_habito" (
  "id_registro" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_habito" int,
  "id_usuario" int,
  "data" date
);

/* tabela de tarefas do dia */
CREATE TABLE "tarefas_do_dia" (
  "id_tarefa" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int,
  "id_habito" int,
  "titulo" varchar NOT NULL,
  "concluida" boolean
);

/* tabela de templates de metas */
CREATE TABLE "templates_metas" (
  "id_template" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int,
  "titulo" varchar,
  "eixo" varchar2,
  "objetivo" varchar,
  "prazo" date
);

ALTER TABLE "interesses" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "habitos" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "registro_habito" ADD FOREIGN KEY ("id_habito") REFERENCES "habitos" ("id_habito");

ALTER TABLE "registro_habito" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "tarefas_do_dia" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "tarefas_do_dia" ADD FOREIGN KEY ("id_habito") REFERENCES "habitos" ("id_habito");

ALTER TABLE "templates_metas" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");
